### ISSUE TITLE
코드 관련된 질문은 아니지만..

### ISSUE THREAD

**Issue by stevenkim18** [ndb796/python-for-coding-test#1]
책 제목을 검색해보니 아직 출판하지 않은 책인데 언제 출간하는 지 궁금합니다^^

**Comment by stevenkim18** [comment]
책 제목을 검색해보니 아직 출판하지 않은 책인데 언제 출간하는 지 궁금합니다^^

**Comment by ndb796** [comment]
안녕하세요, 스티븐님.
본 책은 **2020년 8월 (다음달) 초에 출간 예정**입니다 :)
관심 가져주셔서 감사합니다.

**Comment by stevenkim18** [comment]
오 곧이네요!! 기대 됩니다!! 답변 감사합니다!
