### ISSUE TITLE
[질문]최단 경로 단원 _ 미래도시 문제 _ 다른 풀이 + 건의 사항

### ISSUE THREAD

**Issue by dasd412** [ndb796/python-for-coding-test#10]
문제 해설에서는 플로이드 워셜 알고리즘을 이용할 수 있을 정도로 n이 작기 때문에, 해당 알고리즘으로 풀려있습니다.
저는 다르게 풀었는데요.
K는 반드시 경유하고 X로 가야하기 때문에
start->K까지의 다익스트라 알고리즘 리턴값 + K->X까지의 다익스트라 알고리즘 리턴 값으로 풀었습니다.
물론, 두 가지 중 하나라도 도달할 수 없는 경로면 -1을 출력하고 프로그램을 종료하였습니다.

이렇게 푸는 방식에도 문제가 없겠죠? 

그리고 책은 좋다고 생각하지만, 책에 있는 예제만으로는 테스트를 확실하게 하기 어렵다고 봅니다..
따라서 해당 문제에 대한 사이트 링크를 첨부하여 독자들이 "확실하게"답을 맞출 수 있는지 확인하게 좋다고 봐요.

**Comment by ndb796** [comment]
먼저 말씀해주신 풀이 방법(다익스트라 2번 사용)도 정확한 풀이 방법이 맞습니다.  또한 말씀해주신 바와 같이 책에 있는 예제만으로는 독자 분들이 정답 여부를 판단하기 어려워 하는 것 같아, 스스로 채점해 볼 수 있도록 테스트 데이터 셋을 본 깃허브 저장소에 추가 할 예정입니다.

좋은 피드백 정말 감사합니다.
나동빈 드림
