### ISSUE TITLE
136페이지 탐색 알고리즘 DFS/BFS 부분

### ISSUE THREAD

**Issue by n2ptune** [ndb796/python-for-coding-test#106]
안녕하세요. 오탈자를 발견한 것 같아 이슈 남깁니다.

136페이지 마지막 줄 전 줄에 보시면 **예를 들어 노드 1과 노드 7이 연결되어 있는지 확인해보자........** 이라고 나와있는데, 책에서 설명하는 예제에서 노드는 0, 1, 2 밖에 없습니다.

좋은 책 써주셔서 감사합니다.

**Comment by ndb796** [comment]
안녕하세요, @n2ptune 님!

해당 페이지에서 "<b>예를 들어 노드 1과 노드 7이 연결되어 있는지 확인해보자. 인접 행렬 방식에서는~"</b>라는 문장은 바로 위쪽에 있는 그림 및 코드와는 상관이 없는 문장입니다. 단락을 바꾸어 글을 쓰긴 했지만, 글의 문맥상 위쪽 그림에 대하여 설명한 것처럼 느껴질 수 있겠네요. 그래서 헷갈리신 것 같습니다.

<b>"또 다른 예시로 한 그래프에서 노드 1과 노드 7이 연결되어 있는 상황을 생각해보자. 인접 행렬 방식에서는~</b>"의 의미로 이해해 주시면 감사하겠습니다. 제가 문장을 더 명확하게 쓰지 못하여 헷갈리게 해드린 것 같아 죄송합니다.

피드백 감사합니다.
나동빈 드림

**Comment by n2ptune** [comment]
아하 상관없는 문장이였군요. 알려주셔서 감사합니다.
