### ISSUE TITLE
Chapter7 - 190p 오타

### ISSUE THREAD

**Issue by jhhj424** [ndb796/python-for-coding-test#11]
안녕하세요 신지호입니다.

Chapter7 - 190p 에서 이진탐색 파이썬 코드 맨 윗부분에

if array[mid] == tartget:
    return mid
**# 중간점의 값보다 찾고자 하는 값이 작은 경우 왼쪽 확인**
elif array[mid] > target:
    return binary_search(array, target, start, mid - 1)
**# 중간점의 값보다 찾고자 하는 값이 작은 경우 오른쪽 확인  -> # 중간점의 값보다 찾고자 하는 값이 큰 경우 오른쪽 확인**
    return binary_search(array, target, mid + 1, end)

'# 중간점의 값보다 찾고자 하는 값이 작은 경우 오른쪽 확인' 이 부분에서 "작은 경우"가 "큰 경우"로 변경되어야 할 것 같습니다.

**Comment by ndb796** [comment]
안녕하세요, 신지호 님!

말씀하신 대로 190p의 주석에서 “# 중간점의 값보다 찾고자 하는 값이 작은 경우 오른쪽 확인”이 아니라 "# 중간점의 값보다 찾고자 하는 값이 큰 경우 오른쪽 확인"이 맞습니다.

교재의 잘못된 부분을 바로잡아주셔서 정말 감사드리며, 검토 과정에서 꼼꼼하게 검토를 하지 못하여 불편을 드린 점 정말 죄송합니다.

감사합니다.
나동빈 드림
