### ISSUE TITLE
[질문]위상정렬_커리큘럼_문제 이해

### ISSUE THREAD

**Issue by dasd412** [ndb796/python-for-coding-test#13]
문제 예시를 보니까 최소 시간이 70시간으로 되어 있습니다.
이는 1번 강의 30시간+3번 강의 40시간으로 계산된 것 같은데요.

문제 설명에서 "동시에 여러 개의 강의를 들을 수 있다고 가정한다"라고 되어 있는데,
이는 1번 강의랑 2번 강의를 (예를 들면 같은 학기에 있어서) 동시에 듣는데, 30시간이면 두 강의를 모두 완수할 수 있고
(예를 들면 다음학기의)3번 강의를 들어서 40시간을 들어 총 70시간이라고 보면 될까요?

만약 이렇게 이해한 게 맞다면, 문제 설명을 바꾸는 게 좋을 것 같습니다.
"동시에 여러 개의 강의를 들을 수 있다" 보다는 "같은 학기 내에 있는 강의는 동시에 여러개 들을 수 있다.
예를 들어, 30시간이면 1번 강의와 2번 강의를 모두 들을 수 있다. ~~~~"
가 낫다고 생각합니다.

**Comment by ndb796** [comment]
안녕하세요, dasd412님.

말씀하신 대로 문제 본문의 예시에서는 1번 강의와 2번 강의를 동시에 들을 때 30시간이면 두 강의를 모두 들을 수 있고, 그다음으로 3번 강의를 듣는 데 40시간이 필요하여 총 70시간이 필요하게 됩니다. 따라서 이해하신 내용이 맞습니다.

혹여 문제 이해에 어려움을 느끼셨다면, 문제 설명을 더 친절하게 작성할 수 있도록 노력하겠습니다. 피드백 주셔서 정말 감사합니다 :) 개정판 때 3번 강의를 수강하기까지 필요한 최소 시간이 70시간인 이유에 대해서 설명을 더 자세히 넣어 주면 좋을 것 같다는 생각이 들어, 그렇게 진행하고자 합니다.

다만 dasd412님께서 "학기"라는 내용을 넣으면 좋겠다고 말씀하시는 이유가 무엇인지 자세히 여쭈어봐도 될까요? 개인적으로 학기로 구분된다는 내용을 추가적으로 넣었을 때 문제 이해에 더 많은 시간이 소요될 것 같아서, 생각하시는 다른 그림이 있으신지 궁금하여 글을 남깁니다.

감사합니다.
나동빈 드림

**Comment by dasd412** [comment]
"학기"라는 내용은, 문제가 이해가 잘 안되어 "개인적으로" 해석한 것입니다.
사실, 굳이 문제설명에서 "학기"여야 할 필욘 없다고 보고요. 그래서 저자님이 어떤 방식으로 추가 설명을 넣으시던 간에
독자들의 이해가 더 잘된다면 문제 없을 거라고 생각해요
