### ISSUE TITLE
[DP] p.220 개미전사 문제

### ISSUE THREAD

**Issue by iamcodingcat** [ndb796/python-for-coding-test#133]
교재 220쪽 다이나믹 프로그래밍의 '개미전사' 문제 소스코드에서 ``d[1]``에 왜 ``max(array[0], array[1])``이 들어가나요? 그냥 ``d[1] = array[1]`` 하면 안되나요? 만약 주어지는 식량창고가 ``2 1 1 1 5``가 된다면 두 번째 창고를 털게 된다면 무조건 첫 번째 창고는 털지 못하게 되서 무조건 ``d[1] = 1 ``이지 않나요? 책에서 주어진 해답 소스코드를 따라 간다면 ``d[1] = 1`` 이 아닌 ``2``가 되는데 그러면 안되지 않나요..?
```
n = int(input())
array = list(map(int, input().split()))
d = [0] * 100
# array의 0,1번째 인덱스의 값인 1번째, 2번째 창고 DP 테이블에 기록
d[0] = array[0]
d[1] = array[1]

for i in range(2, n):
    d[i] = max(array[i] + d[i-2], d[i-1])

print(d[n-1])
```

**Comment by wh4044** [comment]
dp를 제대로 이해하시면 왜 그러는지 아실거에용
dp에는 지금까지의 결과 중에서 최대값이 되는것을 담는 겁니다.
예시로 말씀드리면 d[1]의 의미는 두번째까지 털었을 때(두 번째를 털었는지 안털었는지는 모름)의 최대 식량입니다.
질문 주신대로 2 1 1 1 5라면 d[0] = 2, d[1] = 1인데, 이는 dp에 어긋납니다.
첫 번째 식량창고를 털어서 d[0] = array[0]이지만, 두 번째 식량창고는 털어야할지, 말지 모르니까 첫 번째, 두 번째 중에서 더 큰값을 넣어 주는 겁니다.
질문에서는 두 번째 창고를 털면 첫번째 창고를 털지 못하는것은 맞지만, 2 1 1 1 5 예시에서는 첫 번째를 터는게 이득이니까 d[1]에 더 큰값을 넣어주기 위해 max(array[0], array[1])을 해주는 겁니다.

**Comment by iamcodingcat** [comment]
@wh4044 답변 감사드립니다! 이해가 되었어요! DP 테이블에 있는 값들은 무조건 최대 식량값들만이 담기는 거군요! 감사합니다!
