### ISSUE TITLE
p.241 개선된 다익스트라 알고리즘 음수 부호 테크닉 질문

### ISSUE THREAD

**Issue by DoTheBestMayB** [ndb796/python-for-coding-test#150]
p.241 에서 '최소 힙을 최대 힙처럼 사용하기 위해서 일부러 우선순위에 해당하는 값에 음수 부호(-)를 붙여서 넣었다가'라고 되어있는데요.

p.231 에서 "다익스트라 최단 경로 알고리즘은 '음의 간선'이 없을 때 정상적으로 동작한다"라고 되어있습니다.

따라서 음수 부호를 붙이는 테크닉은 잘못된 것 아닌가요?

**Comment by DoTheBestMayB** [comment]
p.455 음수 부호를 붙이는 테크닉의 예제가 있네요.

"음의 간선이 없어야 한다"를 "서로 다른 부호를 가진 간선이 없어야 한다"로 이해하면 되나요?

**Comment by iamcodingcat** [comment]
안녕하세요! 지나가다 최근에 최단경로 알고리즘을 배워서 사견을 댓글로 남겨요! 우선 음수 부호를 붙이는 테크닉과 음의 간선 존재간의 관계는 상관이 없습니다. 예를 들어서, 역으로 최단 경로가 아닌 최대 경로를 구하는 문제라고 해보죠. 우선순위 큐에 음수(-)를 붙이게 되어서 우선순위 큐 안에서 원래는 1, 2, 3, 4로 정렬되어야 할 데이터들이 -4, -3, -2, -1 로 정렬이 됩니다.(음수는 음수에 붙어있는 수가 클수록 작은거 잊지 마세요!) 이 상태에서 다시 우선순위 큐에서 데이터를 빼낼 때 음수(-) 부호를 다시 붙여준다고 했으니 우선순위 큐에서 나올 때는 4, 3, 2, 1로 나오게 되고 결국 최대 힙이 구현이 됩니다!

혹여나 이해가 안가신다면 답글 남겨주세요! : )
