### ISSUE TITLE
Chapter3 - 4번문제 1이 될때까지 코드 확인 부탁드립니다.

### ISSUE THREAD

**Issue by KimTaeHyeong-97** [ndb796/python-for-coding-test#16]
n, k = map(int,input().split())

count = 0 
while True:
  ## n 이 나누어 떨어질때
  if n % k == 0:
    if n == 1:
      break
    n = n / k
    count += 1
  ## n 이 나누어 떨어지지 않을때
  else:
    if n == 1:
      break
    n = n - 1
    count += 1
    
print(count)

저는 이런식으로 작성했는데 test case가 많지 않아서 걱정됩니다..

**Comment by ndb796** [comment]
적어주신 코드도 정답 코드입니다. "현재 상태"를 기준으로 k로 나눌 수 있다면 나누고, 그렇지 않다면 1을 뺀다는 그리디 알고리즘을 구현한 코드네요. 잘 작성하셨습니다.

다만 파이썬에서는 단순히 n / k라고 하면 실수가 반환되므로, 예기치 못한 결과가 나오는 경우를 피하기 위해 다음과 같이 n // k 혹은 int(n / k)라고 적어 주시면 더 좋습니다.

```
n, k = map(int,input().split())

count = 0
while True:
    # n 이 나누어 떨어질때
    if n % k == 0:
        if n == 1:
            break
        n = n // k
        count += 1
    # n 이 나누어 떨어지지 않을때
    else:
        if n == 1:
            break
        n = n - 1
        count += 1

print(count)
```
