### ISSUE TITLE
p118 게임 개발 4-4.py 질문드립니다.

### ISSUE THREAD

**Issue by leeejihyun** [ndb796/python-for-coding-test#173]
안녕하세요. p118 게임 개발 4-4.py에서 질문이 있습니다.

```
        # 뒤로 갈 수 있다면 이동하기
        if array[nx][ny] == 0:
            x = nx
            y = ny
        # 뒤가 바다로 막혀있는 경우
        else:
            break
        turn_time = 0
```

뒤로 갈 수 있다면 이동하는 부분도 가본 칸에 해당하니 count해야 하는 것 아닌가요?
바꾸면 다음과 같습니다.

```
        # 뒤로 갈 수 있다면 이동하기
        if array[nx][ny] == 0:
            x = nx
            y = ny
            count += 1
        # 뒤가 바다로 막혀있는 경우
        else:
            break
        turn_time = 0
```

**Comment by chol0824** [comment]
안녕하세요 ! 혹시 아직 해결 못하신 부분이시라면 설명 드려도 될까요?

**Comment by leeejihyun** [comment]
오 네네 설명해주시면 감사하겠습니다!

**Comment by chol0824** [comment]
제가 이해한 것은
먼저 3번 조건을 보면  이미 네 방향( 동 서 남 북 )에서 안 가본 곳이 없는 상태가 됐을 때 (turn_time = 4) 를 말하는 것입니다 !
그 상태에서 "바다"로 인해서 뒤로 갈 수 없는 경우에 움직임을 멈춘다고 나와있죠 !
즉 뒤가 가본 칸이어도 "바다"로 인해서 갈 수 없는 경우만 아니면 된다는 얘기인 것 같습니다 !
그래서 가 본 위치를 저장하는 배열(교재에서는 d[] )이 아닌 맵의 정보(육지인지 바다인지)를 저장한 배열(arr[] )이 0인지 아닌지만 판단(if array[nx][ny] == 0: )한 것입니다 ! ㅎ

**Comment by leeejihyun** [comment]
엇 저는 뒤가 가본 칸이든 가보지 않은 칸이든 캐릭터가 이동했다면 count에 +1을 해야 한다고 생각해서 질문드렸는데 지금 다시 문제를 읽어보니 count는 캐릭터가 방문한 칸의 수, 즉 가본 칸에 대한 count 같네요. 네 방향 모두 갈 수 없는 경우면 바다를 제외하고 뒤가 무조건 가본 칸이니 이미 count에 포함이 되었겠군요. 이해하는데 도움이 되었습니다. 감사합니다!
