### ISSUE TITLE
깃허브 readme url 매칭에 오류가 있습니다 

### ISSUE THREAD

**Issue by saechimdaeki** [ndb796/python-for-coding-test#2]
readme.md 파일에 적혀있는
Part3 알고리즘 유형별 기출문제의 

11장 그리디 무지의먹방라이브 링크가 https://www.acmicpc.net/problem/2437 백준 저울문제로 되어있습니다
* [무지의 먹방 라이브](https://www.acmicpc.net/problem/2437) (카카오): [Python 3.7 코드](/11/6.py)

아래와 같이변경하여야 할것같습니다 (프로그래머스 링크) https://programmers.co.kr/learn/courses/30/lessons/42891
* [무지의 먹방 라이브](https://programmers.co.kr/learn/courses/30/lessons/42891) (카카오): [Python 3.7 코드](/11/6.py)

**Comment by ndb796** [comment]
수정되었습니다.
잘못된 부분 바로 잡아주셔서 정말 감사합니다 :)
