### ISSUE TITLE
P.201 문제 조건 불일치 

### ISSUE THREAD

**Issue by Rok93** [ndb796/python-for-coding-test#25]
p. 201에서는 M의 범위를  1 <= M <= 2,000,000,000 (20억) 이라고 했는데, 뒷 장에서 설명할 때는 
M이 최대 10억까지 가능하다고 반복적으로 말하고 있습니다. 아마도 앞의 조건이 잘못된게 아닐까 하고 생각이 듭니다.

**Comment by ndb796** [comment]
안녕하세요, Rok93님.

M은 **손님이 요청하는 떡의 길이**를 의미하며,
**개별적인 떡의 높이**는 10억보다 작거나 같은 양의 정수 또는 0입니다.
더불어 문제 조건에서는 떡 높이의 총합이 항상 M 이상이라고 명시하고 있습니다. (항상 답을 도출할 수 있다는 의미)

따라서 개별적인 떡의 높이가 최대 10억이라는 점에서 이진 탐색을 수행할 때의 초기 범위는 10억 이하로 설정됩니다.
그러므로 문제 조건에 오류가 없다는 생각이 듭니다.

혹시 제가 잘못 이해했다면, M이 최대 10억까지 가능하다는 내용이 어느 부분에 기재되어 있는지 여쭈어봐도 될까요?

책 내용을 잘 읽어주시고, 좋은 피드백을 해주셔서 정말 감사합니다!

감사합니다.
나동빈 드림

**Comment by Rok93** [comment]
죄송합니다. 개별적인 떡의 길이가 특정 변수로 주어진게 아니라서 제가 간과한 것 같습니다. (그래서 뒷 부분의 내용을 잘못 받아들인 것 같습니다) 
혼란을 드려 죄송합니다.
