### ISSUE TITLE
p.205 오타로 추정되는 부분 있습니다. 

### ISSUE THREAD

**Issue by Rok93** [ndb796/python-for-coding-test#26]
p.205 첫 문장에서 

"~~같을 때~~마다 H 값을 중간점(MID) 값으로 갱신해주면 된다." (X) --> "**작을 때**마다 H 값을 중간점(MID) 값으로 갱신해주면 된다" 

문맥상 "크거나 같다" 라는 표현이 아니라 "크거나 작은 경우에 중간점이 갱신되는게 맞는 것 같습니다. 

오타가 맞는지 확인 부탁드립니다 : )

**Comment by ndb796** [comment]
"크거나 작은 경우에 중간점이 갱신"이 되어야 한다고 판단하시는 이유가 무엇인지 자세히 말씀해주실 수 있을까요?
**얻을 수 있는 떡의 길이 합**이 **필요한 떡의 길이**와 완전히 같을 때는 멈추어야 하는 게 맞습니다.
다만 완전히 같지 않더라도(얻을 수 있는 떡의 합이 더 큰 경우에도) 그것이 최적의 해일 수도 있어 갱신이 되지 않을 수 있습니다.

중간점은 탐색 범위가 완전히 좁혀져서 더 이상 범위를 좁힐 수 없을 때까지 갱신된다고 보는 것이 맞으며,
본 문제에서는 <b>중간점(MID) = 현재 잘라보고자 하는 높이(H)</b>로 보아야 합니다.

언급해주신 페이지에서  '~때마다 <b>H값</b>을 중간점(MID) 값으로 갱신해주면 된다.'라는 문장에 오류가 있다고 생각합니다.
제가 집필 당시 검토 과정에서 이를 제대로 확인하지 못했네요. 불편을 드린 점 정말 죄송합니다.

이 문장을 '~때마다 <b>결과값(Result)</b>을 현재의 높이 값을 의미하는 중간점(MID)의 값으로 갱신해주면 된다.'는 문장으로 바꾸고자 하며,
앞 부분 또한 문장상 오류가 없도록 수정하고자 합니다. 피드백 정말 감사드리며, 개정판 때 이 내용을 반영하고자 합니다.

혹시 제가 잘못 이해하여 답변 드린 부분이 있다면 말씀해주시면 감사하겠습니다.

좋은 피드백을 해주셔서 정말 감사합니다.
나동빈 드림

**Comment by Rok93** [comment]
이부분은 제가 이분탐색으로 '최적의 해'를 찾는 유형에 덜 익숙해서 착각했던 것 같습니다. 
아직 이분 탐색을 이용하여 최적의 해를 찾는 유형은 낯설게 느껴지는 것 같습니다 : D 
혼란을 드려 죄송합니다.
