### ISSUE TITLE
p.118 게임개발 문제 관련 질문

### ISSUE THREAD

**Issue by Jungry** [ndb796/python-for-coding-test#27]
게임 개발 문제의 답안예시 (p.121) 에 count 의 초기값을 1 로 놓은 이유가 뭔가요 ?_?

**Comment by Jungry** [comment]
시작지점도 방문처리해서 그런건가용 ?!

**Comment by ndb796** [comment]
캐릭터가 방문한 칸의 수를 세야 하므로, 말씀하신 대로 처음 시작 좌표 또한 세주어야 합니다.

그래서 처음에 count 변수의 값을 1로 설정하며,
이후에 가보지 않은 칸으로 이동(새로운 곳으로 이동)할 때마다 count 값을 증가시키는 방법을 사용합니다.

감사합니다.
나동빈 드림
