### ISSUE TITLE
정렬 - 안테나 문제

### ISSUE THREAD

**Issue by world9604** [ndb796/python-for-coding-test#29]
정렬 - 안테나 문제 java 소스가 잘못 되었어요.

Collections.sort(students);   => Collections.sort(arrayList); 

// 중간값(median)을 출력
System.out.println(v[(n - 1) / 2]);  => System.out.println(arrayList[(n - 1) / 2]);

**Comment by ndb796** [comment]
안녕하세요, world9604님.

안테나 문제의 Java 코드에서 오류가 있었습니다.
틀린 부분을 지적해주셔서 정말 감사합니다. 깃허브에 코드 수정 적용되었습니다.

나동빈 드림
