### ISSUE TITLE
구현 -  자물쇠와 열쇠

### ISSUE THREAD

**Issue by world9604** [ndb796/python-for-coding-test#32]
구현 - 자물쇠와 열쇠 문제에서
java 소스에서 rotateMatrixBy90Degree 메서드 에서 
result[j][n - i - 1] = a[i][j];
result의 인덱스가 [j][n - i - 1] 인지 잘 모르겠어요.
설명 좀 해주 실수 있나요? 

그리고 46번째 라인에서
for (int x = 0; x < n * 2; x++)
    for (int y = 0; y < n * 2; y++)
에서 왜 n * 3 까지 탐색을 하지 않고 n * 2 까지 탐색 하는지 설명 해주실 수 있나요?
책, 너무 잘 읽고 있습니다.

**Comment by ndb796** [comment]
먼저 2차원 리스트를 90도 회전하는 함수에서 result[j][n - i - 1] = a[i][j]는 <b>배열 a를 시계 방향으로 90도 회전</b>시킨 결과를 result에 담도록 만들어 줍니다.

더 자세히 설명 드리자면, 원래 배열의 열 정보에 해당하는 j가 결과 배열에서는 행으로 들어가도록 만듭니다. 또한 원래 배열의 행 정보에 해당하는 i가 결과 배열에서는 열에 해당해야 합니다. 단, 순서가 반전되어야 하기 때문에 n - i - 1을 넣습니다.

이 함수는 직접 종이에 2차원 배열을 그려 보신 뒤에, 종이를 시계 방향으로 돌려 보시면 빠르게 이해하실 수 있을 거라고 생각합니다.

<hr>

이어서 반복문에서 n * 2가 사용된 이유에 대해서 말씀드리겠습니다.

일단 우리는 크기가 3배로 변환된 자물쇠에 대하여 왼쪽 위부터 오른쪽 아래까지의 모든 위치에 대하여 차례대로 열쇠를 끼워 넣어야 합니다. 반복문에서 x와 y가 0부터 n * 2 - 1까지 증가하도록 만들면 가능한 모든 경우의 수를 고려할 수 있습니다.

자물쇠에 열쇠를 끼워 넣고자 하는 상황에서, <b>[x][y]는 열쇠의 가장 왼쪽 위 위치</b>를 의미하고, <b>[x + i][y + j]는 열쇠의 가장 오른쪽 아래 위치</b>를 의미한다고 보시면 됩니다. 그렇기 때문에 열쇠가 맵을 벗어나지 않도록 보장하기 위해(인덱스가 벗어나지 않도록 하기 위해) n * 3이 아닌 n * 2가 들어가야 합니다.

감사합니다.
나동빈 드림

**Comment by world9604** [comment]
감사합니다. 이해했습니다.
