### ISSUE TITLE
카카오 무지 먹방 라이브 문제

### ISSUE THREAD

**Issue by world9604** [ndb796/python-for-coding-test#34]
java 소스 코드에서 아래 소스가 잘 이해가 안가는데, 설명해 주실수 있나요?

// summary + (현재의 음식 시간 - 이전 음식 시간) * 현재 음식 개수와 k 비교
while (summary + ((pq.peek().getTime() - previous) * length) <= k) {
        int now = pq.poll().getTime();
        summary += (now - previous) * length;
        length -= 1; // 다 먹은 음식 제외
        previous = now; // 이전 음식 시간 재설정
}

(현재의 음식 시간)에서 (이전 음식 시간)을 왜 빼는지 잘 모르겠습니다.
그리고, summary를 왜 더하는지, 잘 모르겠습니다.

**Comment by ndb796** [comment]
안녕하세요, ~님.

해당 문제 풀이에서 <b>[Step 2]</b> 부분의 내용에 오류가 있었습니다. 불편을 드려 정말 죄송합니다.

<b>[Step 2]</b>의 수정된 내용은 [정오표](https://github.com/ndb796/python-for-coding-test/blob/master/notice.md)에서 확인 부탁드립니다.

이어서 질문해주신 내용에 대하여 답변 드리겠습니다.

본 코드에서는 매 Step마다 (우선순위 큐에서 원소를 꺼낼 때마다) 하나의 음식을 '완전히' 먹어 치운다고 보시면 됩니다. 이때 summary 변수는 이전 Step까지의 음식들을 먹기 위해 소요했던 <b>총 시간</b>을 의미합니다.

우선순위 큐의 최상위 원소인 pq.peek()은 현재의 음식 시간(현재 확인하고 있는 음식을 먹기 위한 시간) 정보를 가지고 있고, 여기에서 previous 변수는 <b>이전 음식에 대한 음식 시간</b>을 의미합니다.

previous를 빼주어야 하는 이유는, 회전판이 돌 때마다 <b>남아있는 모든 음식에 대해서 음식을 먹기 때문</b>입니다. 다시 말해 <b>현재 Step에서 확인하고 있는 음식은 이미 많이 먹은 상태</b>일 수 있습니다. 그러므로 현재 확인하고 있는 음식을 먹기 위한 시간에서 previous를 빼주어, 해당 음식에 대해서 남은 만큼만 먹고자 하는 것입니다.

정리하자면 Java 코드에서 summary + ((pq.peek().getTime() - previous) * length)는 현재의 음식까지 다 먹었을 때, <b>총 소요 시간</b>이 어떻게 될지를 의미합니다. 이것이 K 이하일 때, 현재의 음식도 먹도록 처리하는 것을 알 수 있습니다. 참고로 파이썬이나 C++에서도 동일한 로직으로 작성되었습니다.

질문 글을 남겨주셔서 정말 감사드리고, 교재의 부족한 설명과 잘못된 내용에 대하여 정말 죄송합니다.

나동빈 드림

**Comment by world9604** [comment]
죄송하긴요...책 너무 잘 보고, 유익 합니다! 이슈에 대해서도 정확히 이해 했습니다.
감사 합니다. ^^

**Comment by iamcodingcat** [comment]
지나가다가 도움 얻고 갑니다!
