### ISSUE TITLE
공부 방법에 대해 문의 올립니다.

### ISSUE THREAD

**Issue by asqwklop12** [ndb796/python-for-coding-test#39]
안녕하세여.
나름대로 열심히 한다고 했지만,
이렇게 하는게 맞는지 확인하기 위해 올립니다.

현재 저는 무조건 하루에 3시간은 코테 공부를 하려고 하고 있습니다.
너무  안되는 날에도 최소한 2시간은 하려고 노력합니다. 

근데 제가 구현쪽이 많이 약합니다. 
책을 보니 풀이 시간이 적혀져 있더라구요. 그래서 저는 이 시간동안 최대한 고민해봅니다.
예를들어 풀이 시간이 40분이 적혀 있다면, 
40분동안 문제를 풀고 답을 봅니다. 왜냐하면 문제를 계속 푸는건 의미가 없다고 생각했기 때문입니다.
그리고 문제 상단 오른쪽에 보면 1회,2회,3회 체크하는 부분이 있더라구요.
그래서 문제를 풀었으면(답을 보지 않고) 그곳에 체크 합니다.
그리고 나서 약 2번째 풀때는 4일, 3번째 풀때는 10일정도 있다 문제를 풀고 있습니다.
물론, 답을 본 코드는 체크하지않고, 다음 날에 다시 풀어봅니다.
답을 보지 않고 풀때까지 위 행동을 반복합니다. 그러면 언젠가는 풀리더라구요.
그렇게 체크가 3개가 될때까지 진행하지만,
너무 쉬운 문제는 한번만 풀고 안푸는 경우도 있기는 합니다.

이렇게 공부하는게 나쁘지는 않는것 같은데,
이게 맞는건지 잘 몰라 문의드립니다.

추가적으로 매주 화요일마다 스터디를 진행해 다른 분들이 어떻게 풀었는지 그 풀이를 듣습니다.

**Comment by asqwklop12** [comment]
추가적으로 매주 화요일마다 스터디를 진행해 다른 분들이 어떻게 풀었는지 그 풀이를 듣습니다.

**Comment by ndb796** [comment]
안녕하세요.

알고리즘 공부 방법에 정해진 방법은 없다고 생각하며, asqwklop12님의 공부 방법은 합리적이라고 생각합니다.

사실 구현 쪽은 많은 연습이 필요한 분야고, 다양하게 출제될 수 있기 때문에 아주 오랫동안 많은 문제를 접하신 분들도 복잡한 구현 문제를 만나면 어려워하곤 합니다. 그나마 파이썬 사용에 익숙하시면 구현 유형에는 조금 더 강해지실 수 있습니다.

다만, 풀이 시간과 관련해서는 시간이 넉넉하시다면 기본적인 풀이 시간의 2배 정도만큼은 고민해보시는 것을 추천 드립니다. 예를 들어 풀이 시간이 40분이면, 80분 정도는 고민해 보신 뒤에 답을 보는 것을 추천 드립니다.

그리고 풀었을 때마다 체크하면서, 여러 번 푸시는 지금의 방법은 매우 좋다고 생각합니다. 지금 방식대로 꾸준히 하시면 나중에는 답을 전혀 참고하지 않아도 많은 문제를 푸실 수 있게 되고, 유사한 유형의 문제 또한 풀 수 있게 될 것입니다.

그리고 스터디를 통해서 다른 분들의 풀이와 공유하는 것 또한 매우 좋은 공부 방법인 것 같습니다. 풀이 및 코드를 공유하는 버릇을 기르게 되면, 평소에 별로 신경을 쓰지 않던 코드도 조금 더 효율적으로 바꿀 수 있지 않을까 고민하며 끊임없이 개선할 수 있습니다.

마지막으로 이미 하고 계실지 모르겠지만 별도로 문제 풀이에 사용한 코드는 깃허브 등에 모아 놓으시는 것을 추천 드립니다.

감사합니다.
나동빈 드림

**Comment by asqwklop12** [comment]
넵 감사합니다. 코드는 깃허브에 모아두고 있고, 문제를 어느정도 풀었으면 블로그에 정리까지 하고 있습니다. 감사합니다.
