### ISSUE TITLE
p.226 효율적인 화폐 구성 질문

### ISSUE THREAD

**Issue by asqwklop12** [ndb796/python-for-coding-test#48]
문제를 풀다 궁금한점이 있습니다.

문제에는 [각 화폐는 몇 개라도 사용할 수 있으며... 이하 생략]
이런 것으로 봐서 화폐의 갯수를 구하는 문제이구나 생각했습니다.

그런데 출력 조건이 경우의 수라고 적혀 있어서 이상함에 질문합니다.

예를들어,
동전은 2원과 3원이 존재하구,
4원을 만든다고 생각해보면
4원은 2원 2개가 필요합니다.
즉, 화폐의 개수로 따졌을 때는 2개가 답이지만
경우의 수는 2원 2개만 존재하기 때문에 1이 답이라 생각했습니다.

하지만 이 예제는 15원을 만들기 위한 예제인데..
저와 같이 경우의 수로 계산할시... 정답보다 더 큰 숫자가 나오는게 확인되었습니다.

이에 따라 2가지를 유추해 볼수 있을 것 같습니다.
첫 번째, 책 내용이 오타다.
단순히 오타라고 본다면, 경우의 수가 아니라 화폐의 갯수라고 표현하는게 맞는것 같습니다.

두번째, 계산 실수다.
어쩌면 경우의 수나 화폐의 개수가 같은 의미로 작성되었을지도 모르죠.
또, 15원으로 점차적으로 계산하면서 중복된 내용이 다수 발견 되었습니다.
그렇다는건 중복된 내용을 제거하기만 하면 정답이 될 수 있을 것 같습니다.

하지만, 계산 실수일수도 있지만, 책의 오타일 가능성도 배재할 수 없다고 판단했습니다.
더 정확한 내용이 무엇인지 확인하고자 질문올립니다.
동빈님의 의견은 어떠신가요?

**Comment by ndb796** [comment]
안녕하세요, <b>asqwklop12</b>님.

동일한 내용으로 다른 분께 메일로 피드백을 받았었는데, 정오표에 반영하는 것을 있었네요. 정말 죄송합니다. 말씀하신 대로 본 문제의 출력 조건이 잘못 기재되어 있습니다. 아마 책 교정 과정에서 잘못 기재된 것 같습니다.

올바른 출력 조건은 다음과 같습니다.

> 첫째 줄에 M 원을 만들기 위한 **최소한의 화폐 개수를 출력**한다.

교재의 잘못된 부분을 말씀해주셔서 정말 감사드리며, 검토 과정에서 꼼꼼하게 검토를 하지 못하여 불편을 드린 점 정말 죄송합니다.

감사합니다.
나동빈 드림

**Comment by asqwklop12** [comment]
있었다고 하셔서 깜짝놀랬네요.ㅜㅜ;;
