### ISSUE TITLE
p514 ~ p515 무지의 먹방 라이브 소스코드 관련 질문입니다!

### ISSUE THREAD

**Issue by sirin0762** [ndb796/python-for-coding-test#49]
<source code>
import heapq

def solution(food_times, k):
    if sum(food_times) <= k:
        return - 1
    q = []
    
    for i in range(len(food_times)):
        heapq.heappush(q, (food_times[i], i + 1))
        
    sum_value = 0
    previous = 0
        
    length = len(food_times)
    
    while sum_value + ((q[0][0] - previous) * length) <= k:
        now = heapq.heappop(q)[0]
        sum_value += (now - previous) * length
        length -= 1
        previous = now
    
    result = sorted(q, key = lambda x : x[1])
    return result[(k - sum_value) % length][1]
____________________________________________________________________________
이 문제의 알고리즘의 경우 전체 남은 시간(k) 를 (남은 음식의 수 * 가장 적게 걸리는 음식)으로 뺴는
즉 k = k - (남은 음식 * 가장 적게 걸리는 음식) 을 반복문으로 둬서 k가 더 이상 뺼 수 없을 때
남은 음식을 재정렬 한 뒤(번호순으로) 답을 도출 하는 걸로 알고 있습니다. 
하지만 소스코드를 보면 그런 방식이 아닌거 같아서 코드를 이해하는데에 혼동을 겪고 있습니다. 
while 문의 조건에 대해서 설명해주시면 감사하겠습니다!

**Comment by jsrimr** [comment]
정오표에 나와있다고 합니다! #34

**Comment by sirin0762** [comment]
#jsrimr 감사합니다!!

**Comment by jsrimr** [comment]
Issue close 해주시면 동빈님이 레포 관리하기 좀 더 수월하실거 같아요!
