### ISSUE TITLE
A 01 모험가 길드 문제 문의 드립니다.

### ISSUE THREAD

**Issue by didrlgus** [ndb796/python-for-coding-test#5]
혹시, c++ 답안 코드에서 'if (count >= i)' 하는 부분을 'if (count >= arr[i])' 로 고쳐야 하지 않을까요...?
c++ 정답 코드가  'if (count >= i)' 로 되어 있어서 오타인 것인지 질문 드립니다.

**Comment by ndb796** [comment]
앗, 죄송합니다. 말씀해주신 내용이 맞습니다!
책의 파이썬 코드는 정상이고, 깃허브에 등록된 C++ 코드가 잘못 기재되어 있었습니다.
확인 후 수정하였습니다.

정말 감사합니다 :)
나동빈 드림
