### ISSUE TITLE
프로그램을 테스트하고 싶은데 링크가 없으면 안되나요?

### ISSUE THREAD

**Issue by jsrimr** [ndb796/python-for-coding-test#54]
p.311 의 모험가길드부터 시작하는데 작성한 프로그램을 어디에 제출해서 검증받아야할지 모르겠습니다 ㅠ

링크가 제공된 문제는 프로그램 검증이 가능한데 링크가 없는 문제들은 어떻게 검증할 수 있을까요?

**Comment by ndb796** [comment]
안녕하세요, @jsrimr 님.

링크가 없는 문제들에 대하여 테스트 데이터셋을 만들어 공유하려고 준비 중에 있습니다.
공부하시는 데에 불편을 드려 정말 죄송합니다.

나동빈 드림
