### ISSUE TITLE
그냥 정렬이 아니라 우선순위 큐를 사용하는 이유는 무엇인가요

### ISSUE THREAD

**Issue by jsrimr** [ndb796/python-for-coding-test#55]
무지의 먹방라이브 - p.316 문제를 풀면서 느낀건데 굳이 라이브러리를 써가면서 우선순위큐를 쓰는 이유가 궁금합니다!  그냥 sorted 함수 써서 문제를 푸는 것에 비해 어떤 우위가 있는것일까요?

**Comment by ndb796** [comment]
안녕하세요, @jsrimr 님.

좋은 질문 정말 감사합니다.

말씀하신 대로 본 문제는 우선순위 큐를 이용하지 않고도, 정렬 라이브러리를 사용해 정렬한 뒤에 문제를 해결할 수 있습니다. 저는 해당 코드를 작성하는 과정에서 우선순위 큐를 이용하여 해결하는 방식이 독자 입장에서 더 이해가 쉽다고 생각하여 이를 이용했습니다.

우선순위 큐를 이용하는 솔루션과 단순 정렬을 이용하는 솔루션 모두 시간 복잡도는 <b>O(NlogN)</b>이므로, 원하는 방식으로 문제를 해결하셔도 무방합니다.

감사합니다.
나동빈 드림
