### ISSUE TITLE
챕터 8 - 221p 오타

### ISSUE THREAD

**Issue by dasd412** [ndb796/python-for-coding-test#6]
221p 개미 전사 문제 해설에서
(b)를 보시면, 식량창고를 털 수 있는 경우입니다.

하지만, <-털수 없음으로 표기되어있습니다.

**Comment by ndb796** [comment]
말씀하신대로 그림 ⓑ에서 '털 수 있음'으로 표기되어야 하는데, 잘못 표기되어 있었습니다.
검토 과정에서 꼼꼼하게 검토를 하지 못하여 불편을 드려 정말 죄송합니다.  

감사합니다.
나동빈 드림
