### ISSUE TITLE
Chapter 12 6번 문제 자바 소스가 없습니다.

### ISSUE THREAD

**Issue by jaenyeong** [ndb796/python-for-coding-test#60]
안녕하세요.

쓰신 책을 구매해서 코딩테스트 공부를 하는데 크게 도움을 받고 있어 감사 말씀 드립니다.

다름이 아니라 위 제목처럼 Chapter 12 6번 문제의 자바 소스가 없어 문의 남깁니다.

실제 책 329페이지에 기둥과 보 설치 문제 입니다. 혹시 자바 소스 업로드 가능하실까요?

**Comment by ndb796** [comment]
안녕하세요, @jaenyeong 님!

답변이 늦어 정말 죄송합니다. 빠져 있던 일부 문제에 대한 자바 코드는 모두 추가된 상태입니다.

책에 관심 가져주셔서 너무 감사드립니다. 혹여 다른 필요하신 사항 있으시면 남겨주세요!

감사합니다.
나동빈 드림
