### ISSUE TITLE
Page 488 - 암호 만들기 문제

### ISSUE THREAD

**Issue by world9604** [ndb796/python-for-coding-test#61]
안녕하세요.
Page 488 - 암호 만들기 문제에서 이해가 안가는 점이 있는데요.
1. 암호면, 순서가 상관 있는거 아닌가요? 왜 순열이 아니고, 조합으로 해결하는지 잘 이해가 가지 않습니다.
2. 왜 결과값을 정렬 하는 것이 아니라, 입력 받은 값을 정렬 하고 시작하는지 이해가 가지 않습니다.
도와주시면, 감사하겠습니다.

**Comment by ndb796** [comment]
안녕하세요, @world9604님!

좋은 질문 정말 감사합니다.

#### 1번 질문에 대한 답변

가능한 모든 **순열**이 아닌 **조합**을 찾는 이유는 문제 설명에서 "암호를 이루는 알파벳이 암호에서 증가하는 순서로 배열되었을 것이라고 추측"된다는 문구가 있기 때문입니다.

예를 들어 {a, b, c}가 있다고 하면 a, b, c / a, c, b / b, a, c / b, c, a / c, a, b / c, b, a 중에서 a, b, c만 고려한다는 의미가 되므로 사실상 순서는 고려하지 않고 **모든 조합**을 찾으면 되는 것입니다.

#### 2번 질문에 대한 답변

출력을 할 때는 문자열의 알파벳이 오름차순 형태를 띠어야 하므로 combinations 라이브러리 호출 이전에, 미리 전체 구성을 오름차순 정렬하게 되면 만들어지는 조합들 또한 자동으로 알파벳 기준으로 정렬이 이루어진 상태로 나오게 됩니다.

다음의 코드를 참고해 보시는 것을 추천 드립니다. 실행 결과는 차례대로 ab, ac, bc입니다.

```
from itertools import combinations

arr = ['b', 'c', 'a']
arr.sort()

for candidate in combinations(arr, 2):
    print("".join(candidate))
```

감사합니다.
나동빈 드림

**Comment by world9604** [comment]
감사합니다. 이해했습니다.
항상 답변 달아주셔서 감사합니다.
