### ISSUE TITLE
건의 사항입니다.

### ISSUE THREAD

**Issue by Parkyunhwan** [ndb796/python-for-coding-test#68]
이슈 글을 읽어보니 테스트 셋을 추가해주실 예정이라고 하셨는데 혹시 언제 추가가 될까요?
문제를 풀어도 채점을 할 수가 없어서 아쉽습니다..

책은 잘 보고 있습니다. 감사합니다.

**Comment by ndb796** [comment]
안녕하세요, @Parkyunhwan 님!

건의해 주셔서 정말 감사드립니다.

말씀하신 대로 링크가 없는 문제들에 대하여 테스트 데이터셋을 만들어 공유하려고 준비 중입니다.
다만 테스트 케이스 제작에는 시간이 꽤 필요해서, 개정판이 나올 때 업데이트 가능할 것 같습니다.

나동빈 드림

**Comment by Parkyunhwan** [comment]
답변 감사합니다.
