### ISSUE TITLE
197p 부품 찾기 문제 질문있습니다

### ISSUE THREAD

**Issue by Sungho-Wi** [ndb796/python-for-coding-test#7]
이진탐색 문제로써
쓰여진 정답을 보면은 N개의 리스트를 (1 <= N <= 1000000) 일단 정렬하고
M개의 리스트에 (1 <= M <= 1000000) 있는 각 요소들을 이진탐색한다고 나와있는데요

해설지에보면은 정렬시 O(NlogN) 하고 
부품 탐색 시 O(MlogN) 이므로 결국은 O((M+N)logN)이라고 되어있는데요
최악의 경우에는 N에 백만 M에 백만해서
2000000 x log1000000 이므로 20억번이 되는데 시간 제한이 1초라고 되어있어서

1초에 10억번을 처리하므로 해당 알고리즘으로는 해결이 안되는것같은데
혹시 제가 계산에 틀린걸까요?

**Comment by ndb796** [comment]
안녕하세요, 위성호님.

2,000,000 * log 1,000,000은 20억이 아닌 40,000,000 정도의 값이라고 보시면 좋습니다.
이진 탐색 시간 복잡도에서의 log의 밑은 2입니다. 따라서 log 1,000,000은 약 20이라고 보시면 간단합니다. (2의 20제곱이 약 1,000,000이므로) 아마 log와 제곱근(square) 연산을 헷갈리신 것 같습니다.

제가 책에 설명을 불친절하게 넣었나 죄송한 마음이 드네요.
좋은 피드백 감사합니다.
나동빈 드림

**Comment by Sungho-Wi** [comment]
답변해주셔서 감사합니다
오랜만에 수학하려하니 제곱근하고 로그하고 헷갈렸네요 부끄럽습니다... 😅

**Comment by Sungho-Wi** [comment]
답변 감사합니다

오랜만에 수학 식을 보느라 로그하고 제곱근하고 착각했나보네요 부끄럽습니다 ... 😅
책 보면서 도움 많이되고있어요 화이팅입니다

요 이슈는 지워주시면 감사하겠습니다 ㅎㅎ

**Comment by ndb796** [comment]
앗~ 아닙니다! ㅎㅎㅎ 저도 정말 자주 하는 실수에요. 소수(Prime Number) 관련 알고리즘에서는 또 제곱근(Square)까지 처리하거나 하는 일이 있어서... 저도 가끔 제곱근과 로그 함수가 헷갈리곤 합니다!

피드백 감사합니다.
나동빈 드림
