### ISSUE TITLE
1이 될때까지 답안 질문입니다.

### ISSUE THREAD

**Issue by c11g** [ndb796/python-for-coding-test#70]
질문 포인트는  아래인데요.
```py
# 마지막으로 남은 수에 대하여 1씩 빼기
result += (n - 1)
```
주석내용으로 미루어보면 n이 0이 아닌 n<k(탈출조건) 를 만족하는 케이스가 있다고 느껴지는데요.

제가 해보면 while문에서 빠져나올때 아래코드로 인해 항상 n이 0 이 되는것 같아요.
```py
target = (n//k) * k
n = target
```

그렇다면 `result -= -1` 이면 될거 같은데, 혹시 제가 잘못이해하고 있는걸까요?

**Comment by ndb796** [comment]
안녕하세요, @c11g 님!

정답 예시 코드의 마지막 부분에서는 n과 1의 차이만큼 다시 result에 더해줍니다.

while문을 탈출했을 때 n의 값은 0이 되기 때문에, 말씀하신 대로 단순히 result에서 1을 빼줘도 결과는 동일합니다. (`result -= 1`인데, `result -= -1`로 잘못 작성하신 것 같습니다.)

좋은 의견 감사합니다.
나동빈 드림

**Comment by c11g** [comment]
아하 넵, 코드 구현의 차이를 제가 괜히 어렵게 생각을 했나보네요;;
답변 고맙습니다. 그리고 좋은 강의 감사합니다 :)
