### ISSUE TITLE
p.390 숨바꼭질 모범 답안 오류

### ISSUE THREAD

**Issue by Parkyunhwan** [ndb796/python-for-coding-test#79]
[숨바꼭질 모범 답안 링크](https://github.com/ndb796/python-for-coding-test/blob/master/17/4.py)
```python
for i in range(1, n + 1):
    if max_distance < distance[i]:
        max_node = i
        max_distance = distance[i]
        result = [max_node]
    elif max_distance == distance[i]:
        result.append(i)

print(max_node, max_distance, len(result))
```

숨바꼭질 모범답안 마지막에 답안 출력코드가 있는데 해당 코드는 아예 가지 못하는 노드(`INF`)를 처리해주지 못하는 것 같습니다.

for 문 안에 아래 코드를 추가해줘야 하지 않나요?
```python
    if distance[i] == INF:
        continue
```
> 예시 입력
```
6 6
3 6
4 3
3 2
1 3
1 2
2 4
```

**Comment by ndb796** [comment]
안녕하세요, @Parkyunhwan 님!

좋은 질문 감사합니다.

해당 숨바꼭질 문제 설명에서는 "<b>전체 맵은 항상 어떤 헛간에서 다른 어떤 헛간으로 도달이 가능한 형태로 주어집니다.</b>"라고 명시되어 있습니다. 그러므로 다익스트라 최단 경로 알고리즘을 수행한 뒤에도 최단 거리의 값이 그대로 INF인 노드는 존재하지 않게 됩니다.

따라서 일반적인 다익스트라 최단 경로 알고리즘을 수행할 때처럼 초기의 최단 거리의 값을 INF로 설정하는 것은 동일하나, 정답을 출력할 때는 이를 고려하지 않아도 되는 것입니다.

감사합니다.
나동빈 드림
