### ISSUE TITLE
p.115 ~ p.117 왕실의 나이트 문제 java 소스코드 오류

### ISSUE THREAD

**Issue by jhhj424** [ndb796/python-for-coding-test#8]
p.115 ~ p.117 왕실의 나이트 문제 풀이중 깃허브 저장소에 올라와있는 java 소스코드에서 오류가 있는 것 같습니다.

![image](https://user-images.githubusercontent.com/46177529/89734854-a9b0a900-da99-11ea-8a0f-24f987e4e3a3.png)

int column = inputData.charAt(0) - 'a' ;    부분을
int column = inputData.charAt(0) - 'a' + 1;    로 수정해야 맞을 것 같습니다.

혹시 제가 틀리다면 피드백 부탁드리겠습니다.

**Comment by ndb796** [comment]
안녕하세요, jhhj424님.

**왕실의 나이트** 문제의 C++ 및 Java 코드에서 column 변수를 초기화하는 라인에서 오류가 있었습니다. 
틀린 부분을 지적해주셔서 정말 감사합니다. 깃허브에 코드 수정 적용되었습니다.

나동빈 드림

**Comment by jhhj424** [comment]
> 안녕하세요, jhhj424님.
> 
> **왕실의 나이트** 문제의 C++ 및 Java 코드에서 column 변수를 초기화하는 라인에서 오류가 있었습니다.
> 틀린 부분을 지적해주셔서 정말 감사합니다. 깃허브에 코드 수정 적용되었습니다.
> 
> 나동빈 드림

빠른 피드백 감사합니다.

저번에 자바 소스코드 관련 메일드린 신지호 입니다. 
책 정말 유용하게 읽고, 실습 진행중입니다. 
초판이라 완벽하지 않을 수 있겠지만 내용자체로는 정말 훌륭하다고 생각이 듭니다. (가히 코테준비용 책중에 가장 좋다고 생각이 듭니다)
좋은 책 써주셔서 감사합니다.

신지호 드림

**Comment by ndb796** [comment]
피드백 해주셔서 정말 감사합니다.
또한 많이 부족한데... 좋게 봐주셔서 감사합니다.

나동빈 드림
