### ISSUE TITLE
Chater 4-1 상하좌우 질문

### ISSUE THREAD

**Issue by SwimmingHwang** [ndb796/python-for-coding-test#9]
안녕하세요

상하좌우를 아래처럼 풀었는데 
제가 놓친 부분이 있을 것 같아서요
혹시 이렇게 풀었을 때 해당 문제에서 문제 될 부분이 있나요?

```
n= int(input())
arr = list(input().split())

y, x = 1, 1
for a in arr:
    if a == 'R' and x != n:
        x += 1
    elif a == 'L' and x != 1:
        x -= 1
    elif a == 'U' and y != 1:
        y -= 1
    elif a == 'D' and y != n:
        y += 1

print(y,x)
```

**Comment by ndb796** [comment]
안녕하세요! 작성하신 소스코드도 정답입니다 :)

특정한 공간에서 이동하는 형태의 문제를 풀 때는  방향 벡터 목적으로 다음과 같은 리스트 변수를 이용하는 것이 일반적입니다.

dx = [0, 0, -1, 1]
dy = [-1, 1, 0, 0]

하지만 상하좌우 문제는 로직이 매우 간단하기 때문에 질문자님이 적어주신 코드로도 정답 판정을 받을 수 있습니다. 잘 작성하셨습니다. 책에 있는 예제만으로는 독자분들이 정답 여부를 판단하기 어려워하는 것 같아, 스스로 채점해 볼 수 있도록 테스트 데이터 셋을 본 깃허브 저장소에 추가 할 예정입니다.

나동빈 드림
