### ISSUE TITLE
P.369 공유기 설치 문제 모범답안 오류

### ISSUE THREAD

**Issue by YoonKiBum** [ndb796/python-for-coding-test#96]
안녕하세요 나동빈님
동빈님 책으로 열심히 공부하고 있는 대학생 입니다. 다름이 아니라 p.369 공유기 설치 문제 모범답안에 오류가 있는것 같습니다.
책에 있는 파이썬 모범답안으로 문제를 푸니 82% 정도에서 오답이 되더군요. 아무래도 테스트 케이스가 새로 추가된것 같습니다.
5 3
1
7
8
9
10
이 입력으로 들어올 경우 1, 7, 10 이 세곳에 공유기를 설치하여 가장 인접한 거리인 3이 출력이 되어야 하지만, 모범답안에서는
start = array[1] - array[0]으로 지정하고 있기 때문에 mid를 최소 6부터 설정하게 되어서 start보다 작은 3은 고려하지 않게 되고
결과적으로 0을 출력하여 오답처리를 받게 됩니다. 
따라서 문제에서 집 여러개가 같은 좌표를 가지는 일은 없다고 하였으므로 start = 1, end = array[-1] - array[0]으로 설정하는것이 
보다 바람직한 모범답안으로 생각됩니다. 확인 부탁드려요~

**Comment by ndb796** [comment]
안녕하세요, @YoonKiBum 님!

소중한 피드백 정말 감사합니다.

말씀하신 대로 start 변수의 초기화 값이 잘못되어 있었습니다. 문제 풀이 설명은 맞는데, 모범답안을 작성할 때 실수했네요. 잘못된 소스코드로 인해 불편함을 드려 정말 죄송합니다. 더불어 틀린 부분을 지적해주셔서 정말 감사합니다!

다음과 같이 소스코드가 변경되었습니다.

<pre>
start = 1 # 가능한 최소 거리(min gap)
end = array[-1] - array[0] # 가능한 최대 거리(max gap)
</pre>

감사합니다.
나동빈 드림
